### ISSUE TITLE
Move `/status` to private port (8051)

### ISSUE THREAD

**Issue by rcrowe** [configcat/configcat-proxy#17]
### Is your feature request related to a problem? Please describe.

`/status` provides health of the API which feels like private information for something like K8s health probes that I want to expose on `:8051` & not `:8050`

### Describe the solution you'd like

If you agree with the change & given the beta nature, a breaking move can take place.
Else, configuration to allow it to be made private.

**Comment by z4kn4fein** [comment]
Hi @rcrowe, thank you for reporting this! I was also thinking about the same. I'll move the status and the metrics endpoints to the same port (default `:8051`). I'll also merge their configuration under a `diag` node like:
```yml
diag:
  port: <int>
  enabled: <bool>
    status:
      enabled: <bool>
      ...
    metrics:
      enabled: <bool>
      ...
```
